[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "9.8.0"  # Or whatever version you're using

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200